name: ci-build

on:
  push:
    tags:
      - "*"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-go-build:
    runs-on: ubuntu-latest

    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # Doc: https://github.com/marketplace/actions/setup-go-environment
      - uses: actions/setup-go@v3

      # Go Build
      - run: go build -v ./...

  ci-docker-build:
    runs-on: ubuntu-latest

    steps:
      # Doc: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # Doc: https://github.com/marketplace/actions/docker-login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Doc: https://github.com/marketplace/actions/docker-setup-buildx
      - uses: docker/setup-buildx-action@v2

      # Doc: https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:latest
